// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ContactsDBContext))]
    [Migration("20230610112020_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0-preview.4.23259.3");

            modelBuilder.Entity("Domain.Models.ContactInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR (36)")
                        .HasColumnOrder(1);

                    b.Property<string>("CorporatePhoneNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(11);

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(5);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(12);

                    b.Property<int>("EmployeeRegistrationNumber")
                        .HasColumnType("INT")
                        .HasColumnOrder(4);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(3);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(7);

                    b.Property<string>("OtherWorkPhoneNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(10);

                    b.Property<int>("Position")
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(8);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("WorkPhoneNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(9);

                    b.HasKey("Id");

                    b.ToTable("ContactInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
